/**
 * AI Writer API - Content Generation
 */
import { createApiHandler, validateRequiredFields } from '../../lib/api-handler';
import { callAIWithFallback } from '../../lib/ai-providers';

export default createApiHandler({
  methods: 'POST',
  handler: async (req, res) => {
    if (!validateRequiredFields(req, res, ['topic'])) return;

    const { topic, contentType = 'blog-post', tone = 'professional', length = 'medium', keywords = '', audience = '' } = req.body;

    const lengthGuide = { short: '200-300 words', medium: '500-700 words', long: '1000-1500 words', detailed: '2000+ words' };

    const systemPrompt = `You are an expert content writer for the music industry, specializing in royalty management, artist development, and music business. Write in a ${tone} tone. Target audience: ${audience || 'music industry professionals'}. Length: ${lengthGuide[length] || '500 words'}.${keywords ? ` Include these keywords naturally: ${keywords}` : ''}`;

    const contentPrompts = {
      'press-release': `Write a professional press release about: ${topic}\n\nInclude: headline, dateline, lead paragraph, body with quotes, boilerplate, and contact info.`,
      'blog-post': `Write a compelling blog post about: ${topic}\n\nInclude: engaging title, introduction hook, structured sections with headers, key takeaways, and conclusion with CTA.`,
      'social-media': `Create social media content about: ${topic}\n\nGenerate posts for: Instagram (with hashtags), Twitter/X (concise), LinkedIn (professional), and TikTok (trendy). Include emoji suggestions.`,
      'email': `Write a professional email about: ${topic}\n\nInclude: subject line, greeting, clear body, call-to-action, and professional sign-off.`,
      'marketing': `Write marketing copy about: ${topic}\n\nInclude: headline, subheadline, key benefits, social proof elements, and strong CTA.`,
      'bio': `Write a professional artist/company bio about: ${topic}\n\nInclude: background, achievements, style/genre, notable collaborations, and current projects.`,
      'pitch-deck': `Create pitch deck content about: ${topic}\n\nInclude: executive summary, problem/solution, market opportunity, business model, traction, team, and ask.`,
      'contract': `Draft a legal document outline about: ${topic}\n\nInclude: parties, terms, obligations, compensation, IP rights, termination, and dispute resolution. Note: This is a template, not legal advice.`,
      'newsletter': `Write a newsletter about: ${topic}\n\nInclude: subject line, preview text, greeting, main story, secondary items, CTA, and footer.`,
      'lyrics': `Write song lyrics about: ${topic}\n\nInclude: verse 1, chorus, verse 2, chorus, bridge, final chorus. Consider rhythm, rhyme scheme, and emotional impact.`,
      'script': `Write a video/podcast script about: ${topic}\n\nInclude: hook/intro, main content sections, transitions, key talking points, and outro with CTA.`,
      'seo': `Write SEO-optimized content about: ${topic}\n\nInclude: SEO title, meta description, H1-H3 headers, keyword-rich body, internal linking suggestions, and FAQ section.`,
    };

    const prompt = contentPrompts[contentType] || contentPrompts['blog-post'];

    const result = await callAIWithFallback({
      prompt,
      systemPrompt,
      geminiOptions: { maxOutputTokens: 4096 },
      openaiOptions: { maxTokens: 4096 },
    });

    if (result) {
      return res.status(200).json({ content: result.text, provider: result.provider });
    }

    return res.status(200).json({
      content: generateLocalContent(topic, contentType, tone),
      provider: 'local'
    });
  }
});

function generateLocalContent(topic, type, tone) {
  return `# ${topic}

## Overview

This content was generated by the GOAT Royalty AI Writer. To unlock full AI-powered content generation with advanced language models, configure your API keys:

- **Google Gemini**: Set GOOGLE_AI_API_KEY in your .env file
- **OpenAI GPT-4**: Set OPENAI_API_KEY in your .env file

## About This Feature

The AI Writer supports 12 content types including press releases, blog posts, social media content, emails, marketing copy, artist bios, pitch decks, legal documents, newsletters, song lyrics, video scripts, and SEO content.

### Content Type: ${type}
### Tone: ${tone}
### Topic: ${topic}

---

*Configure your AI API keys to generate full, professional content tailored to your needs.*

**GOAT Royalty App** — Powered by SuperNinja AI`;
}
